### ISSUE TITLE
extract css doesn't detect function calls

### ISSUE THREAD

**Issue by yoshuawuyts** [stackcss/css-extract#7]
e.g. this doesn't work:

``` js
const insertCSS = require('insert-css')
insertCSS('html, body { height: 100%; }')
```

from https://github.com/yoshuawuyts/bankai/issues/49

**Comment by ahdinosaur** [comment]
hmm, that's weird. `static-module` should be doing the heavy lifting here and definitely supports function calls like that.

**Comment by goto-bus-stop** [comment]
we're now 2 static-module major versions in the future and i can't repro this, so it's probably fixed. thanks!
